In [2]:
import numpy as np #numpy means numerical  python

In [3]:
np

<module 'numpy' from 'C:\\Users\\chethan\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

## Creating  a matrix 


In [4]:
x=np.array([10,20,30],[40,50,60],[70,80,90])

ValueError: only 2 non-keyword arguments accepted

In [5]:
x=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [6]:
print(x)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
x[0,1]

20

In [8]:
x[1,2]

60

In [10]:
print(x[0]) ##access the entire row

[10 20 30]


## Slicing


In [ ]:
## X[a,b] a is row and bth column

## x[a1:a2,b1:b2]

In [13]:
y= x[0:2,0:2]

In [12]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
y


array([[10, 20],
       [40, 50]])

In [15]:
y.shape ##provides its dimension helps when you have large datax


(2, 2)

In [16]:
x


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [20]:
## accessing the columns

x[:,2]

array([30, 60, 90])

In [21]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Adding  2 matrices


In [25]:
x


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
z


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print(np.add(x,z))

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [32]:
print(np.dot(x,z))   ## multiplication

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


## transpose of matrix

In [34]:
print(np.transpose(x))

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [36]:
print(x)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## creating zeros and ones

In [40]:
w=np.zeros((3,3), dtype = complex)

In [41]:
print(w) # In putput 0. means float

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [42]:
type(w[0,0])

numpy.complex128

In [44]:
## lets create matrix of 1's
a=np.ones((2,2),dtype= int)
print(a)

[[1 1]
 [1 1]]


# iterating  through the array elements
# one way  is nested for loops
# anoother way is using function called nditer()

In [47]:
## nested for loop

for i in  x:    ##[10,20,30]
    for j  in  i:
        print(j)
    #print(i)

10
20
30
40
50
60
70
80
90


In [48]:
#instead of neste for loop we use nditer()
for  i in  np.nditer(x):
    print(i)

10
20
30
40
50
60
70
80
90


## Concatenate  a 2 matrix 

In [49]:
x


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [50]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr1= np.concatenate((x,z))

In [56]:
## concatenate thorough columns

arr2 =np.concatenate((x,z),axis = 1)

In [60]:
arr1.shape

(6, 3)

In [61]:
arr2.shape

(3, 6)

In [64]:
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [65]:
print(arr2)

[[10 20 30  1  2  3]
 [40 50 60  4  5  6]
 [70 80 90  7  8  9]]


In [63]:
## arrange -> a range

np.arange(1,6)

array([1, 2, 3, 4, 5])

In [68]:
np.arange(1,6,2,dtype=complex)

array([1.+0.j, 3.+0.j, 5.+0.j])